version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-react-app
    container_name: react_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
  